publish_url: http://localhost:8001/api/publish
wechime_url: http://localhost:8001/api/publish/wechime
client_id: client_id
client_secret: client_secret
topics:
  - 0
speech_key: speech_balloon
silent_key: thought_balloon
wechime_key: japanese_goblin
voice_keys: !!map
  angry: "mei_angry"
jingle_keys: !!map
  bell: "bell01"
maximum_length: !!null 40