database:
  dsn: postgresql://postgres:postgres@127.0.0.1:5432/mintz
  max_connections: 10

link:
  icon_dir: public/icon
  icon_url: http://localhost:8001/
  sound_dir: public/sound
  audio_url: http://localhost:8001/
  default_icon: http://localhost:8001/public/icon/default.png
  default_audio: http://localhost:8001/public/voice/default.mp3

type_talk:
  topic_id: 0
  token: typetalk bot token

cross_domain:
  origin: http://localhost:8001/

open_jtalk:
  dict_dir: path to directory of dictionaries
  voice_dir: path to directory of voices
  out_dir: path to directory to output audio relative to application root
  voices: !!map
    voiceProperty:
      path: path to voice file under voice_dir
      description: text explaining the feature of the voice

wechime:
  gpio_dir: path to directory of GPIO virtual files
  gpio_chime1: 5
  gpio_chime2: 6
  gpio_chime12: 13