version: '3'
services:
  app:
    build: ./app
    volumes:
      - ./app/mintz:/mintz
      - mintz_stack:/root/.stack:cached
    working_dir: /mintz
    command: /root/.local/bin/stack build :mintz-exe
    ports:
      - 18001:8001
    container_name: mintz_server
volumes:
  mintz_stack: