name:                mintz
version:             0.1.0.0
github:              "githubuser/mintz"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mintz#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - containers
  - monad-control
  - transformers
  - transformers-base
  - template-haskell
  - safe-exceptions
  - time
  - utf8-string
  - bytestring
  - text
  - filepath
  - directory
  - case-insensitive
  - http-conduit
  - http-media
  - http-api-data
  - servant
  - servant-server
  - servant-options
  - wai
  - wai-cors
  - warp
  - HDBC
  - yaml
  - aeson
  - lens
  - extensible
  - monad-logger
  - fast-logger
  - yaml
  - vault
  - convertible
  - hedis
  - parsec
  - cryptonite
  - process
  - network
  - connection
  - websockets
  - hs-graph
  - hs-resource
  - hs-orm
  - hs-template
  - hs-ext-servant

default-extensions:
  - DataKinds
  - KindSignatures
  - TypeOperators
  - TypeFamilies
  - FlexibleContexts
  - FlexibleInstances
  - TypeApplications
  - MultiParamTypeClasses
  - ImplicitParams

library:
  source-dirs: src

executables:
  mintz-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -ddump-splices
    dependencies:
    - mintz

  mintz-daemon:
    main:                Main.hs
    source-dirs:         daemon
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -ddump-splices
    dependencies:
    - mintz

tests:
  mintz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mintz
    - hspec
